export default {
  accountName: null,
  accountType: null,
  pinArray: [],
  pinConfirmArray: [],
  salt: null,
  seed: {},
  pinHash: null,
  pinHashConfirm: null,
  spvMode: null,
  accountLocale: null,
  accountIpNode: null,
  accountCurrency: null,
  getStartedModalOpened: false,
};
