export default {
  sendCoinModalOpened: false,
  sendConfirmModalOpened: false,
  sendConfirmTxData: null,
  sendFailureModalOpened: false,
  sendSuccessModalOpened: false,
  addErc20ModalOpened: false,
  priceChartModalOpened: false,
  selectAccountModalOpened: false,
  newAccountModalOpened: false,
  termsModalOpened: false,
  receiveCoinModalOpened: false,
  addWalletModalOpened: false,
  selectCurrencyModalOpened: false,
  selectLanguageModalOpened: false,
  deleteAccountModalOpened: false,
  newPinModalOpened: false,
  newTxData: null,
  addFundsModalOpened: false,
  updateEmailModalOpened: false,
};
