const etherscanToken = process.env.ETHERSCAN_TOKEN;

export default {
  ETHEREUM: {
    name: 'ETHEREUM',
    segwit: false,
    bip: 60,
    provider: 'https://mainnet.infura.io/v3/352fc30cd8364caabaea4a3d67da773f',
    etherscan: 'http://api.etherscan.io/api',
    etherscanKey: etherscanToken,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 3,
    ens: true,
  },
  ETHEREUM_CLASSIC: {
    name: 'ETHEREUM_CLASSIC',
    segwit: false,
    bip: 60,
    provider: 'https://www.ethercluster.com/etc',
    etherscan: 'https://blockscout.com/etc/mainnet/api',
    etherscanKey: null,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 1,
  },
  XDAI: {
    name: 'XDAI',
    segwit: false,
    bip: 700,
    provider: 'https://dai.poa.network',
    etherscan: 'https://blockscout.com/poa/xdai/api',
    etherscanKey: null,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 100,
  },
  POA: {
    name: 'POA',
    segwit: false,
    bip: 178,
    provider: 'https://core.poa.network',
    etherscan: 'https://blockscout.com/poa/core/api',
    etherscanKey: null,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 99,
  },
  ETHEREUM_ROPSTEN: {
    name: 'ETHEREUM_ROPSTEN',
    segwit: false,
    bip: 60,
    provider: 'https://ropsten.infura.io/v3/352fc30cd8364caabaea4a3d67da773f',
    etherscan: 'http://api-ropsten.etherscan.io/api',
    etherscanKey: etherscanToken,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 3,
    ens: true,
  },
  ETHEREUM_KOVAN: {
    name: 'ETHEREUM_KOVAN',
    segwit: false,
    bip: 60,
    provider: 'https://kovan.infura.io/v3/352fc30cd8364caabaea4a3d67da773f',
    etherscan: 'http://api-kovan.etherscan.io/api',
    etherscanKey: etherscanToken,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 42,
    ens: true,
  },
  ETHEREUM_RINKEBY: {
    name: 'ETHEREUM_RINKEBY',
    segwit: false,
    bip: 42,
    provider: 'https://rinkeby.infura.io/v3/352fc30cd8364caabaea4a3d67da773f',
    etherscan: 'http://api-rinkeby.etherscan.io/api',
    etherscanKey: etherscanToken,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 4,
    ens: true,
  },
  ETHEREUM_GOERLI: {
    name: 'ETHEREUM_GOERLI',
    segwit: false,
    bip: 42,
    provider: 'https://goerli.infura.io/v3/352fc30cd8364caabaea4a3d67da773f',
    etherscan: 'http://api-goerli.etherscan.io/api',
    etherscanKey: etherscanToken,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 5,
    ens: true,
  },
  POA_SOKOL: {
    name: 'POA Sokol',
    segwit: false,
    bip: 178,
    provider: 'https://sokol.poa.network',
    etherscan: 'https://blockscout.com/poa/sokol/api',
    etherscanKey: null,
    feeApi: 'https://api.blockcypher.com/v1/eth/main',
    chainId: 77,
  },
};
