export default [
  {
    displayName: 'Litecoin',
    name: 'Litecoin',
    sdk: 'Bitcoin',
    coinType: 1,
    symbol: 'LTC',
    network: 'LITECOIN_TESTNET',
    denomination: '0.00000000',
  },
  {
    displayName: 'Dash',
    name: 'Dash',
    sdk: 'Bitcoin',
    coinType: 1,
    symbol: 'DASH',
    network: 'DASH_TESTNET',
    denomination: '0.00000000',
  },
  {
    displayName: 'Bitcoin',
    name: 'Bitcoin',
    sdk: 'Bitcoin',
    coinType: 0,
    symbol: 'BTC',
    network: 'BITCOIN_TESTNET',
    denomination: '0.00000000',
  },
  {
    displayName: 'Ethereum',
    name: 'Ethereum',
    sdk: 'Ethereum',
    coinType: 60,
    symbol: 'ETH',
    network: 'ETHEREUM_ROPSTEN',
    denomination: '0.000000000000000000',
  },
  {
    displayName: 'Catalyst',
    name: 'Catalyst',
    sdk: 'ERC20',
    parentSdk: 'Ethereum',
    symbol: 'CAT',
    contractAddress: '0x26705403968a8c73656a2fed0f89245698718f3f',
    decimals: 3,
    parentName: 'Ethereum',
    network: 'ETHEREUM_ROPSTEN',
    denomination: '0.00000000',
  },
];
